name: PR
on: pull_request

jobs:
  conventional:
    if: ${{ false }} # disable for now
    name: Conventional PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - uses: beemojs/conventional-pr-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
